### ISSUE TITLE
How to use network?

### ISSUE THREAD

**Issue by nifanfa** [shafzhr/SimpleOS#1]

**Comment by shafzhr** [comment]
Could you please elaborate what do you mean by using network?
My main goal was controlling 2 NICs and receiving/transmitting raw packets with both. From there, you can improve it your way.
Anyway, I'd happily accept any bug fixes and improvements so feel free to suggest anything.

**Comment by nifanfa** [comment]
um actually i'm trying to implement rtl8139 driver for MOSA-Core and i'm refers to your driver. but it seems won't receive any packet. but it is able to send packet. so i'm thing about how would you use network

**Comment by nifanfa** [comment]
and this is my code btw https://github.com/nifanfa/MOSA-Core/blob/master/Source/Mosa.External.x86/Driver/Network/RTL8139.cs
